### ISSUE TITLE
Common Artist layer planning

### ISSUE THREAD

**Issue by v0dro** [SciRuby/rubyplot#1]
@Arafatk and @pgtgrly discuss common Artist layer APIs in this thread.

-- EDIT 20 June 2018

As per discussion between @Arafatk  and @pgtgrly , we will implement common scripting layer and differing artist classes.

**Comment by v0dro** [comment]
I have an idea - you can build the common API by writing rspecs and then using the same specs in your respective GR and rmagick libraries. That way you can maintain consistency across libraries the whole time.

We'll just establish a protocol that you should not change the specs without communicating with the others. The common specs can be kept in this ruby plot repo and both of you can copy paste it in your repos for now.

**Comment by Arafatk** [comment]
I mean that's certainly possible when we are using a few common normalization functions on the data because we consider those functions as common for both the libraries. So perhaps it's a good idea to add a common specs folder with common testing functions.    
Obviously, all the visual specs for RMagicks and all geometry specs are going to be different.

**Comment by mohawkjohn** [comment]
Yes. This is what I was hoping would happen all along. Sorry for not being
clearer. :)

**Comment by Arafatk** [comment]
If you are referring to the data normalization specs and a few data
transformations then yes, we can certainly do that.  Pranav and I talked
about this a long time ago. Then our projects went totally orthogonal so I
only focussed on my own work.

My code is very intertwined with RMagick Geometry problem but data
transformations steps are still separate for the most part so having that
as a common API won't be a problem as mentioned in my previous email.

**Comment by v0dro** [comment]
@Arafatk you can write the artist specs here: https://github.com/SciRuby/rubyplot/blob/master/spec/artist_spec.rb

**Comment by v0dro** [comment]
Ok so if I understand you correctly @Arafatk is going to refactor his artist classes as the scripting layer?

**Comment by mohawkjohn** [comment]
A couple of thoughts:

1. You all still aren't following the Ruby style. Should be `clear_all!`, not `clearall`, for example. Please go through this and figure out how to make it look like Ruby code.
2. `savefig` does not follow the principle of lease surprise. Why not just `save`?
3. `BarPlot`, not `Barplot`. 
4. You wrote: "# data representation will have charts cannot be multiple over a figure # data plotting can be". What?
5. You have `@marker_colour` and `@marker_size`. What happens if you have two types of marks, e.g. a line plot where the actual data values are marked by an x? I think you need to differentiate between markers and lines.
6. Can you please go back and look at how matplotlib does these things? This is why I want you two to start with a spec before anything else. The spec should include lots and lots of example plots, so you can see exactly what features you need to implement and prevent collisions. Your goal should be to implement, in as few lines of code as possible, as many of the spec'd plots as possible.

cc @Arafatk

**Comment by v0dro** [comment]
I would like to see some Pull Requests opened on this repo contributing to the common scripting layer specs from both @pgtgrly  and @Arafatk.
